### ISSUE TITLE
Logo is lop sided

### ISSUE THREAD

**Issue by daniel-samson** [madmorrison/foodcom#5]
In the readme the logo rotation appears to incorrect.

<img width="123" alt="Screenshot 2020-11-28 at 23 29 59" src="https://user-images.githubusercontent.com/12231216/100528182-b7697600-31d1-11eb-92db-b7e91d40716f.png">

**Comment by madmorrison** [comment]
Where are you accessing the readme that the logo is appearing in the wrong orientation? I have checked the readme on here (github) and have not seen the same issue. 
![notlopsided](https://user-images.githubusercontent.com/74337025/100533535-a4f03c00-31d3-11eb-9596-cc0970af038a.PNG)

**Comment by daniel-samson** [comment]
Might be just my browser
